const projects = [
  {
    id: 'project3',
    title: 'FinBiz Trailblazers Program',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2025',
    liveLink: 'https://finbiz.adaniuniversity.edu/trailblazers',
    company: 'Adani Innovation Hub',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Intensive leadership residency where students collaborate with Adani Innovation Hub mentors on live strategy sprints.',
      'Participants deliver research-backed proposals on energy, infrastructure, and finance transformations.',
      'The cohort concludes with a capstone showcase presented to university leadership and venture partners.',
    ],
  },
  {
    id: 'project4',
    title: 'Fintech Futures Summit',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    date: '2025',
    company: 'Fintech Connect Alliance',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Flagship conference bringing together founders, product designers, regulators, and students to map the future of finance.',
      'Hosted design sprints on embedded finance, compliant AI, and financial inclusion with expert facilitators.',
      'Summit insights were published as an open-source playbook circulated across partner universities.',
    ],
  },
  {
    id: 'project5',
    title: 'Capital Quest Simulation League',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2024',
    company: 'Market Mentors Collective',
    liveLink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Gamified investing league where teams trade live markets with risk management checkpoints.',
      'Mentored by professional traders who conduct debrief masterclasses after each round.',
      'Leaderboard analytics feed into placement readiness reports and certificate pathways.',
    ],
  },
  {
    id: 'project1',
    title: 'Campus Venture Lab Demo Day',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    date: '2024',
    company: 'Campus Venture Lab',
    livelink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Incubation showcase featuring five student-founded startups spanning sustainability, fintech, and consumer tech.',
      'FINBIZ coached teams on financial modelling, storytelling, and investor Q&A readiness.',
    ],
  },
  {
    id: 'project2',
    title: 'Policy & Markets Colloquium',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2023',
    company: 'Regulators Roundtable',
    liveLink: 'https://finbiz.adaniuniversity.edu/colloquium',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Multi-day academic forum analysing policy shifts in digital public infrastructure and their market impact.',
      'Student research papers were peer reviewed by regulators and corporate strategists.',
      'Sessions culminated in policy recommendation whitepapers shared with government liaisons.',
    ],
  },
];
export default projects;
